sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t brianclyde11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brianclyde11/docker-react npm run test
